MASK = '[MASK]'
BERT_UNK = '[UNK]'
BERT_CLS = '[CLS]'
BERT_SEP = '[SEP]'
BERT_PAD = '[PAD]'
MAX_CONTEXT_LEN = 100
INIT_WORD = 'the'
BERT_EMB_DIM = 28996

SPECIAL_SYMBOLS = [
    MASK,
    BERT_UNK,
    BERT_CLS,
    BERT_SEP,
    BERT_PAD
]
