trainer: 'finetune'
args:
    seed: 0
    model_name: 'albert-xxlarge-v2'
    train: 'data/LittleGLUE/SST-2/train_4.jsonl'
    dev: 'data/LittleGLUE/SST-2/dev_4.jsonl'
    test: 'data/LittleGLUE/SST-2/dev_all.jsonl'
    checklist: null
    template: '{sentence} [T] [T] [P] [T]'
    label_map: '{"0": "terrible", "1": "great"}'
    label_field: 'label'
    preprocessor: null 
    evaluation_strategy: 'classification'
    finetune_mode: []
    evaluation_metric: 'accuracy'
    skip_train: False
    skip_eval: False
    skip_test: False
    bsz: 2
    epochs: 30
    disable_dropout: False
    clip: 1.0
    limit: null
    force_overwrite: True
    quiet: False
    tmp: True
parameters:
    accumulation_steps: [1, 2, 4]
    lr: [1.0e-5, 5.0e-5, 1.0e-4, 5.0e-4]
